/**
* Sidebar include
* ------------------
*/
(function(){

var str='';
str+='<!-- sidebar : mobile -->';
str+='<aside id="sidebar">';
str+='	<a href="#nolink" role="button" class="close_sidebar"><i class="fa fa-close"></i><span class="blind">메뉴 닫기</span></a>';
str+='	<div class="sidebar_wrap">';

str+='		<!-- login_area -->';
str+='		<div class="login_area">';
str+='			<h1><a href="#nolink"><span class="blind">한국기독교 장로회 한신교회</span></a></h1>';
str+='			<ul class="login">';
str+='				<li><a href="#nolink" role="button">로그인</a></li>';
str+='				<li><a href="#nolink" role="button">회원가입</a></li>';
str+='			</ul>';
str+='			<ul class="logout">';
str+='				<li><a href="#nolink" role="button">로그아웃</a></li>';
str+='				<li><a href="#nolink" role="button">회원정보</a></li>';
str+='			</ul>';
str+='		</div>';
str+='		<!-- //login_area -->';
str+='		<div class="util_area num2">';
str+='			<ul class="">';
str+='				<li><a href="javascript:void(0)"><i class="icon i01"></i><strong>한신 신학심포지엄</strong></a></li>';
str+='				<li><a href="javascript:void(0)"><i class="icon i02"></i><strong>한신 성서대학</strong></a></li>';
str+='			</ul>';
str+='		</div>';

str+='		<!-- sidebar_menu -->';
str+='		<div class="sidebar_menu">';
str+='			<!-- dep1_wrap -->';

str+='			<div class="dep1_wrap">';
str+='				<ul class="dep1 clearfix">';
str+='					<li>';
str+='						<a href="#nolink"><i class="icon icon01"></i><span>교회소개</span></a>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><i class="icon icon02"></i><span>예배와 찬양</span></a>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><i class="icon icon03"></i><span>사역과 선교</span></a>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><i class="icon icon04"></i><span>커뮤니티</span></a>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><i class="icon icon05"></i><span>교육</span></a>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><i class="icon icon06"></i><span>온라인 사무국</span></a>';
str+='					</li>';
str+='				</ul>';
str+='			</div>';
str+='			<!-- //dep1_wrap -->';

str+='			<!-- dep2_wrap -->';
str+='			<div class="dep2_wrap">';
str+='				<ul class="dep2">';
str+='					<li>';
str+='						<a href="#nolink"><span>교회안내</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>교회역사</span></a></li>';
str+='							<li><a href="#nolink"><span>5대 사역목표</span></a></li>';
str+='							<li><a href="#nolink"><span>신년사</span></a></li>';
str+='							<li><a href="#nolink"><span>고 이중표 목사 추모관</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li><a href="#nolink"><span>담임목사</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>담임목사 소개</span></a></li>';
str+='							<li><a href="#nolink"><span>담임목사 저서</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><span>교회를 섬기는 이들</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>교역자 소개</span></a></li>';
str+='							<li><a href="#nolink"><span>사무직원 소개</span></a></li>';
str+='							<li><a href="#nolink"><span>장로소개</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li><a href="#nolink"><span>교회소식</span></a></li>';
str+='					<li><a href="#nolink"><span>교회주보</span></a></li>';
str+='					<li>';
str+='						<a href="#nolink"><span>교회생활도우미</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>교회 예식 안내</span></a></li>';
str+='							<li><a href="#nolink"><span>신앙교육 안내</span></a></li>';
str+='							<li><a href="#nolink"><span>새가족 안내</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li><a href="#nolink"><span>행복한 사람들</span></a></li>';
str+='					<li><a href="#nolink"><span>한신사진첩</span></a></li>';
str+='					<li><a href="#nolink"><span>부속기관</span></a></li>';
str+='					<li><a href="#nolink"><span>예배시설</span></a></li>';
str+='					<li><a href="#nolink"><span>예배안내</span></a></li>';
str+='					<li><a href="#nolink"><span>오시는길</span></a></li>';
str+='				</ul>';

str+='				<ul class="dep2">';
str+='					<li>';
str+='						<a href="#nolink"><span>예배</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>주일설교영상</span></a></li>';
str+='							<li><a href="#nolink"><span>주일설교원고</span></a></li>';
str+='							<li><a href="#nolink"><span>수요성경공부</span></a></li>';
str+='							<li><a href="#nolink"><span>어머니기도회</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><span>찬양</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>주일예배찬양</span></a></li>';
str+='							<li><a href="#nolink"><span>열린찬양</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='				</ul>';

str+='				<ul class="dep2">';
str+='					<li><a href="#nolink"><span>	사역부 소개</span></a></li>';
str+='					<li>';
str+='						<a href="#nolink"><span>신도회 소개</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>공지사항</span></a></li>';
str+='							<li><a href="#nolink"><span>사진첩</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><span>찬양대소개</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>시온찬양대</span></a></li>';
str+='							<li><a href="#nolink"><span>할렐루야찬양대</span></a></li>';
str+='							<li><a href="#nolink"><span>글로리아찬양대</span></a></li>';
str+='							<li><a href="#nolink"><span>샬롬찬양대</span></a></li>';
str+='							<li><a href="#nolink"><span>열린찬양대</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li><a href="#nolink"><span>	나눔과봉사 소개</span></a></li>';
str+='					<li><a href="#nolink"><span>	해외선교현황</span></a></li>';
str+='					<li><a href="#nolink"><span>	해외선교소식</span></a></li>';
str+='					<li>';
str+='						<a href="#nolink"><span>선교사 추모관</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>순교 태국 선교사 안수한</span></a></li>';
str+='							<li><a href="#nolink"><span>순교 태국 선교사 장현진</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='				</ul>';

str+='				<ul class="dep2">';
str+='					<li>';
str+='						<a href="#nolink"><span>시온찬양대</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>게시판</span></a></li>';
str+='							<li><a href="#nolink"><span>사진첩</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><span>할렐루야 찬양대</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>게시판</span></a></li>';
str+='							<li><a href="#nolink"><span>사진첩</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><span>글로리아 찬양대</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>게시판</span></a></li>';
str+='							<li><a href="#nolink"><span>사진첩</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><span>샬롬 찬양대</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>게시판</span></a></li>';
str+='							<li><a href="#nolink"><span>사진첩</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><span>행복한사람들</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>게시판</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><span>교육국</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>전체공지</span></a></li>';
str+='							<li><a href="#nolink"><span>교육국 소식</span></a></li>';
str+='							<li><a href="#nolink"><span>영유아부 게시판</span></a></li>';
str+='							<li><a href="#nolink"><span>유치부 게시판</span></a></li>';
str+='							<li><a href="#nolink"><span>유년부 게시판</span></a></li>';
str+='							<li><a href="#nolink"><span>초등부 게시판</span></a></li>';
str+='							<li><a href="#nolink"><span>소녀소년부 게시판</span></a></li>';
str+='							<li><a href="#nolink"><span>중등부 게시판</span></a></li>';
str+='							<li><a href="#nolink"><span>고등부 게시판</span></a></li>';
str+='							<li><a href="#nolink"><span>청년부 게시판</span></a></li>';
str+='							<li><a href="#nolink"><span>영어예배부 게시판</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='				</ul>';

str+='				<ul class="dep2">';
str+='					<li>';
str+='						<a href="#nolink"><span>영유아부</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>소개</span></a></li>';
str+='							<li><a href="#nolink"><span>공지사항</span></a></li>';
str+='							<li><a href="#nolink"><span>주보</span></a></li>';
str+='							<li><a href="#nolink"><span>사진첩</span></a></li>';
str+='							<li><a href="#nolink"><span>자료실</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><span>유치부</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>소개</span></a></li>';
str+='							<li><a href="#nolink"><span>공지사항</span></a></li>';
str+='							<li><a href="#nolink"><span>주보</span></a></li>';
str+='							<li><a href="#nolink"><span>사진첩</span></a></li>';
str+='							<li><a href="#nolink"><span>자료실</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><span>유년부</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>소개</span></a></li>';
str+='							<li><a href="#nolink"><span>공지사항</span></a></li>';
str+='							<li><a href="#nolink"><span>주보</span></a></li>';
str+='							<li><a href="#nolink"><span>사진첩</span></a></li>';
str+='							<li><a href="#nolink"><span>자료실</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><span>초등부</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>소개</span></a></li>';
str+='							<li><a href="#nolink"><span>공지사항</span></a></li>';
str+='							<li><a href="#nolink"><span>주보</span></a></li>';
str+='							<li><a href="#nolink"><span>사진첩</span></a></li>';
str+='							<li><a href="#nolink"><span>자료실</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><span>소녀소년부</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>소개</span></a></li>';
str+='							<li><a href="#nolink"><span>공지사항</span></a></li>';
str+='							<li><a href="#nolink"><span>주보</span></a></li>';
str+='							<li><a href="#nolink"><span>사진첩</span></a></li>';
str+='							<li><a href="#nolink"><span>자료실</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><span>중등부</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>소개</span></a></li>';
str+='							<li><a href="#nolink"><span>공지사항</span></a></li>';
str+='							<li><a href="#nolink"><span>주보</span></a></li>';
str+='							<li><a href="#nolink"><span>사진첩</span></a></li>';
str+='							<li><a href="#nolink"><span>자료실</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><span>고등부</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>소개</span></a></li>';
str+='							<li><a href="#nolink"><span>공지사항</span></a></li>';
str+='							<li><a href="#nolink"><span>주보</span></a></li>';
str+='							<li><a href="#nolink"><span>사진첩</span></a></li>';
str+='							<li><a href="#nolink"><span>자료실</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><span>청년부</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>소개</span></a></li>';
str+='							<li><a href="#nolink"><span>공지사항</span></a></li>';
str+='							<li><a href="#nolink"><span>주보</span></a></li>';
str+='							<li><a href="#nolink"><span>사진첩</span></a></li>';
str+='							<li><a href="#nolink"><span>자료실</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='					<li>';
str+='						<a href="#nolink"><span>영어예배부</span></a>';
str+='						<ul class="dep3">';
str+='							<li><a href="#nolink"><span>소개</span></a></li>';
str+='							<li><a href="#nolink"><span>공지사항</span></a></li>';
str+='							<li><a href="#nolink"><span>주보</span></a></li>';
str+='							<li><a href="#nolink"><span>사진첩</span></a></li>';
str+='							<li><a href="#nolink"><span>자료실</span></a></li>';
str+='						</ul>';
str+='					</li>';
str+='				</ul>';

str+='				<ul class="dep2">';
str+='					<li><a href="#nolink"><span>기부금 증명서 신청</span></a></li>';
str+='					<li><a href="#nolink"><span>행정사무 안내</span></a></li>';
str+='				</ul>';
str+='			</div>';
str+='			<!-- //dep2_wrap -->';
str+='		</div>';
str+='		<!-- //sidebar_menu -->';
str+='	</div>';
str+='</aside>';
str+='<!-- //sidebar : mobile -->';


document.write(str);


})();
